version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5454
  #     - DB_USER=sharq
  #     - DB_PASSWORD=sharq
  #     - DB_NAME=sharq
  #   depends_on:
  #     - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=hommy
    ports:
      - "5454:5432"