"""Add study_form

Revision ID: 76eee8be7957
Revises: f1e4ee2242a5
Create Date: 2025-07-02 13:41:01.986209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76eee8be7957'
down_revision: Union[str, Sequence[str], None] = 'f1e4ee2242a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index(op.f('ix_study_languages_id'), table_name='study_languages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_study_languages_id'), 'study_languages', ['id'], unique=False)
    op.drop_table('study_forms')
    # ### end Alembic commands ###
