"""Correct change relashinship_4

Revision ID: d6879874a66c
Revises: 77e5227d8c4d
Create Date: 2025-07-02 17:50:42.040024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6879874a66c'
down_revision: Union[str, Sequence[str], None] = '77e5227d8c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_info_id', sa.Integer(), nullable=False),
    sa.Column('passport_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passport_data_id'], ['passport_data.id'], ),
    sa.ForeignKeyConstraint(['study_info_id'], ['study_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
