"""Add study_lenguage

Revision ID: f1e4ee2242a5
Revises: 2c905aff10a0
Create Date: 2025-07-02 13:22:48.686286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e4ee2242a5'
down_revision: Union[str, Sequence[str], None] = '2c905aff10a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_study_languages_id'), 'study_languages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_languages_id'), table_name='study_languages')
    op.drop_table('study_languages')
    # ### end Alembic commands ###
