"""Correct relashinship

Revision ID: f9397fee652a
Revises: d4d8d9bf16f2
Create Date: 2025-07-02 15:24:05.141641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9397fee652a'
down_revision: Union[str, Sequence[str], None] = 'd4d8d9bf16f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passport_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passport_series_number', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('issuing_authority', sa.String(length=100), nullable=False),
    sa.Column('authority_code', sa.String(length=10), nullable=False),
    sa.Column('place_of_birth', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_form_id', sa.Integer(), nullable=False),
    sa.Column('study_direction_id', sa.Integer(), nullable=False),
    sa.Column('study_form_id', sa.Integer(), nullable=False),
    sa.Column('study_language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_form_id'], ['exam_forms.id'], ),
    sa.ForeignKeyConstraint(['study_direction_id'], ['study_directions.id'], ),
    sa.ForeignKeyConstraint(['study_form_id'], ['study_forms.id'], ),
    sa.ForeignKeyConstraint(['study_language_id'], ['study_languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_info')
    op.drop_table('passport_data')
    op.drop_table('users')
    # ### end Alembic commands ###
